Getting the 'Libraries' binaries from S3
tari-project/tari-dot-com-old pull request #20
Opened 2020-06-18 13:54 UTC by shanimal08

## Description

Getting the libs data from S3 and rendering it (only for Libraries at the moment)

#### Screenshots

It looks the same but... :)

![image](https://user-images.githubusercontent.com/47271333/85028910-fd7ad200-b17b-11ea-9be3-25a8e6f7bc13.png)

2020-06-18 15:07 UTC, Krakaw requested changes

2020-06-18 15:07 UTC, Krakaw commented on _includes/downloads.html
> +                        SHA256: {{ os.checksum }}
This changes with every file, it needs to come from the API

2020-06-19 08:07 UTC, Krakaw requested changes

2020-06-19 08:07 UTC, Krakaw commented on _includes/downloads.html
> +                    <a class="btn" id="{{ os.downloadBtnID }}">{{os.ctaText}}</a>
Where's the href?

2020-06-19 10:35 UTC, shanimal08 commented on _includes/downloads.html
> +                    <a class="btn" id="{{ os.downloadBtnID }}">{{os.ctaText}}</a>
It gets added in in the JS on line 81 😬

2020-06-26 05:58 UTC, Krakaw approved these changes
LGTM!

2020-06-26 06:52 UTC, CjS77 approved these changes
Nice

2020-06-26 06:53 UTC, merged